const DEFAULT_YANDEX_METRIKA_ID = "109712823";

export const YANDEX_METRIKA_ID =
  process.env.NEXT_PUBLIC_YANDEX_METRIKA_ID?.trim() || DEFAULT_YANDEX_METRIKA_ID;

export const YANDEX_METRIKA_COUNTER_ID = Number(YANDEX_METRIKA_ID);
